### ISSUE TITLE
dead project

### ISSUE THREAD

**Issue by Amdingo** [JetBrains/teamcity-aws-codebuild-plugin#3]
Seems like it is, just want to confirm?

**Comment by VladRassokhin** [comment]
@Amdingo Why do you think so?

**Comment by Amdingo** [comment]
no readme, no info of any kind and importing into teamcity doesn't seem to provide codebuild as an agent or runnertype which is what I would expect it to do.  

If I'm incorrect in some way though please let me know!

**Comment by winstonaws** [comment]
+1 - I tried importing it into TeamCity as well, and although it shows up on the Plugins List, I can't add it as a runner in build steps.

ANY documentation on how to use this would be greatly appreciated.

**Comment by erick-thompson** [comment]
I'm running into the same. I'm not sure if this plugin is dead, or something else is going on.

**Comment by juris** [comment]
Hello. Is there anybody out there?

**Comment by vbedrosova** [comment]
Hi guys, could you please create an issue in TeamCity bug tracker https://youtrack.jetbrains.com/issues/TW and attach teamcity-server.log log file
